### PR TITLE
fix failure in migration build

### PR DESCRIPTION
**Pull request by hartb**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hartb** [comment]
Closes: #6

**Comment by hartb** [comment]
Trying to migrate this to aarch64 and ppc64le.

Migration PR (#6) submitted by the bot failed for lack of 'make'. This PR includes the same content from the bot's PR, but with an extra commit to add make as a build dependency.

**Comment by hartb** [comment]
Hello @isuruf, this is a replacement PR for a migration bot PR (#6) that had failed for lack of 'make'.

Is this an OK way to amend that, and would it normally merge without human intervention?

Thank you!

**Comment by kmuehlbauer** [comment]
@hartb I'm currently the sole maintainer of this ~~package.~~ feedstock. Would you consider being a maintainer too?

**Comment by hartb** [comment]
@kmuehlbauer I'm just getting started with forge, so not sure of the maintainer responsibilities. Let me study the docs a bit and think about it.

**Comment by kmuehlbauer** [comment]
@conda-forge-admin, please rerender

**Comment by kmuehlbauer** [comment]
@hartb

I haven't the slightest idea why the azure builds in #6 for linux and osx are working smoothly and the aarch64/ppc64le builds complain about missing build program. The packages installed seem identical. 

As this (adding make) was recommended at the confa-forge gitter channel, I think we can follow that line.

Nevertheless, maybe @conda-forge/arm-arch can shed some light on this?

**Comment by kmuehlbauer** [comment]
@hartb I'll merge this later today, just trying to get some more feedback from the arch guys. Being a maintainer gives you the ability to merge this stuff at your own convenience in accordance to the conda-forge rules. The more maintainers the earlier pull requests get reviewed or action is taken, if something happens. Your help is appreciated in any case, either as maintainer or one time collaborator.

**Comment by jayfurmanek** [comment]
I think the difference is because make is not included in the forge image for the new arches, while it is elsewhere. I don't know the reasoning behind *that*  - maybe an effort to reduce the image size.

**Comment by kmuehlbauer** [comment]
@jayfurmanek Thanks for chiming in, that makes sense somehow.

**Comment by jjhelmus** [comment]
`make` is requirement of `yum` in CentOS 6 so it cannot be removed from the x86_64 image without removing `yum`.  In CentOS 7 this is no longer true so the aarch64 and ppc64le images do not include `make`.  Packages that require `make` should declare that dependency in the recipe rather than relying on the system version.

**Comment by jayfurmanek** [comment]
Ah! So that's why! Thanks for the explanation @jjhelmus !

**Pull request merged**
