### PR TITLE
Windows build

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge/help-c-cpp

Any idea why with VC2008, the library files are `libaec.lib` and with VC2015 they are `aec.lib`?

I could just skip the old 2008 build.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by kmuehlbauer** [comment]
@hmaarrfk Would you mind adding yourself as maintainer. I'm not a Windows guy so I would appreciate your support.

**Comment by hmaarrfk** [comment]
done.

Ultimately. i just want to be able to install imagecodecs on conda-forge.

That package is so hard to build....

**Comment by kmuehlbauer** [comment]
Thanks, similar here, needed it for eccodes package.

Let's have a look how this bot merge works.

**Pull request merged**
